dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: "XuanCe_DiffPPO_Algorithm"
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "qkhanh711"
render: False
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
fps: 50
test_mode: False
device: "cuda"  # Choose an calculating device. PyTorch: "cpu", "cuda:0"; TensorFlow: "cpu"/"CPU", "gpu"/"GPU"; MindSpore: "CPU", "GPU", "Ascend", "Davinci".
distributed_training: False  # Whether to use multi-GPU for distributed training.
master_port: '12355'  # The master port for current experiment when use distributed training.

agent: "DiffPPOAgent"
env_name: "UAVLLMOffloadingEnv"
env_id: "new_env_id"
env_seed: 1
vectorize: "DummyVecEnv"
learner: "DiffusionPPOLearner"
policy: "DiffusionPPOPolicy"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [256,]
activation: 'leaky_relu'
activation_action: 'tanh'

seed: 19089
parallels: 2
buffer_size: 50000
batch_size: 256

# Optimizer
learning_rate: 0.0002
actor_learning_rate: 0.0002
critic_learning_rate: 0.0006

# Diffusion-PPO specific
n_timesteps: 10
beta_schedule: "linear"
ema_decay: 0.99
step_start_ema: 500
update_ema_every: 3
tau: 0.95
clip_param: 0.2
beta_diffusion: 0.5
value_loss_coef: 0.25
old_policy_sync: 10
critic_updates: 3

# Replay / training schedule
gamma: 0.99
training_frequency: 1
running_steps: 15000
start_training: 512

use_grad_clip: True  # gradient normalization
grad_clip_norm: 1.0
grad_norm: 1.0
use_actions_mask: False
use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "logs/diffppo/"
model_dir: "models/diffppo/"